// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACol: typeof import('ant-design-vue/es')['Col']
    ARow: typeof import('ant-design-vue/es')['Row']
    Bar: typeof import('./src/components/Bar.vue')['default']
    Dasbord: typeof import('./src/components/Dasbord.vue')['default']
    Line: typeof import('./src/components/Line.vue')['default']
    Map: typeof import('./src/components/Map.vue')['default']
    Numerical: typeof import('./src/components/Numerical.vue')['default']
    Projecter: typeof import('./src/components/Projecter.vue')['default']
    Projection: typeof import('./src/components/Projection.vue')['default']
    Round: typeof import('./src/components/Round.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
